version: "3.1"

services:
  mysql-docker-container:
    image: mysql/mysql-server:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: loans
    volumes:
      - /data/mysql
    ports:
      - "3306:3306"

  xloans-api:
    image: xloans-api-image:latest
    container_name: xloans-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - "8080:8080"
    volumes:
      - /data/spring-boot-app