db:
  host: mysql-container
  port: 3306
  schema: loans
  username: root
  password: root

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: loans
  datasource:
    validationQuery: SELECT 1


server.port: 8080

logging.level:
  br.com.srm: DEBUG