#Configuracoes com pool de conexao no banco de dados e limites de Timeout
spring:
  profiles.active: local
  datasource:
    hikari:
      connection-timeout: 4000
      idle-timeout: 60000
      #Rever a necessedade do pool size - cada aplicacao deve ter uma demanda diferente
      maximum-pool-size: 20
      minimum-idle: 7
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    url: jdbc:mysql://${db.host}:${db.port}/${db.schema}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate.use-new-id-generator-mappings: false
    properties.hibernate.jdbc.time_zone: GMT-3
    show-sql: false
  output.ansi.enabled: always
  main.banner-mode: log

server.port: 8080

management.endpoints:
  web.base-path: /monitor
  health.show-details: always

info.application:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  build-timestamp: '@project.build.timestamp@'

logging.level:
  br.com.srm.xloansapi: info
  org:
    springframework.web: error
    hibernate: error
  io.lettuce: error

server.tomcat:
  max-connections: 20000
  max-threads: 20000